GO_GOROUTINE = "Goroutine"
GO_CGO_CALL = "GoCgoCall"
GO_GC_COUNT = "GoGcCount"
GO_GC_PAUSE = "GoGcPause"
GO_HEAP_USED = "GoHeapUsed"

TPS = "GoTPS"
ELAPSED_TIME = "GoElapsedTime"
ERROR_RATE = "GoErrorRate"
ACTIVE_SERVICE = "GoActiveService"
ACTIVE_SPEED = "ActiveSpeed"
